local API_KEY = { token = "API_KEY" } -- for Anonymous SignUp Test 

local function check_json()
	local test_data = { 
		['ss_01'] = {
			[1] = {
				mouse = {
					dx = 0,
					dy = 0,
					mL = 0,
					mR = 0
				}
			}
		}
	}
	-- encode table -> json 
	print(cjson.encode(test_data))
end

local firebase_auth = require('firebase.auth')
local firebase_database = require('firebase.database')

function init(self)
	local auth = firebase_auth:new('bool-8ba6d')
	auth:auth_service_account('/KEY.json', 60 * 60, function(session)
		--
		-- create new database instance
		--
		local database = firebase_database:new(session)
		print(session.ACCESS_TOKEN)	
		
		database:get('/users/000', function(res)
			print('test_get: ' .. res.status)
		end)
		database:put('/users/000', function(res)
			print('test_put: ' .. res.status)
		end, { ['test_put'] = true })

		database:post('/users/000', function(res)
			print('test_post: ' .. res.status)
		end, { ['test_post'] = true })

		database:delete('/users/000/test_put', function(res)
			print('test_delete: ' .. res.status)
		end)
		
	end)
end

