local API_KEY = { token = "AIzaSyCfzQJ3lKBEcNhpmDEyB19S7WJuY_LzW74" }

local function check_json()
	local test_data = { 
		['ss_01'] = {
			[1] = {
				mouse = {
					dx = 0,
					dy = 0,
					mL = 0,
					mR = 0
				}
			}
		}
	}
	-- encode table -> json 
	print(cjson.encode(test_data))
end

function init(self)
	--
	-- create new database instance
	--
	local database = require('firebase.database')
	local fb = database:new('bool-8ba6d')
	-- fb:auth_service_account('private_key.json')
	--
	-- request token and execute requests:
	--
	fb:request_token(API_KEY.token, function()
		--
		-- test GET 
		--
		fb:get('/users/000', function(res)
			print('test_get: ' .. res.status)
		end)
		--
		-- test PUT 
		--
		fb:put('/users/000', function(res)
			print('test_put: ' .. res.status)
		end,
		{ ['test_put'] = true })
		--
		-- test POST
		--
		fb:get('/users/000', function(res)
			print('test_post: ' .. res.status)
		end,
		{ ['test_post'] = true })
		--
		-- test DELETE 
		--
		fb:delete('/users/000/test_put', function(res)
			print('test_delete: ' .. res.status)
		end)
	end)
end

